CREATE TABLE topicos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(200) NOT NULL,
    mensaje VARCHAR(2000) NOT NULL,
    fecha_creacion DATETIME NOT NULL,
    status VARCHAR(30) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    curso VARCHAR(120) NOT NULL,
    PRIMARY KEY (id)
);
